export default [
  { name: "Advisor Admin Form", location: "http://bkdcontactcenter.host/advisoradmin/" },
  { name: "Aspect Disposition Codes", location: "http://teams.brookdaleliving.com/sites/sla/Systems Guides/Aspect/Aspect Disposition Codes.htm" },
  { name: "BAH Referral Form", location: "https://bkdcontactcenter.host/cc-bhs-pl-referral-form/" },
  { name: "BKD Webinar Sign Up", location: "https://www.brookdale.com/en/meetings/webinar.html" },
  { name: "CC Helpful Numbers", location: "http://teams.brookdaleliving.com/sites/sla/Quick%20Reference%20Guides/CC%20Helpful%20Numbers%202.12.19.htm" },
  { name: "CC Rate Finder", location: "http://edge.assisted.com/#/views/RateFinderUpdate/RateFinder?:iid=1" },
  { name: "Community Profiles", location: "https://bkdcontactcenter.host/community-profile-look-up/" },
  { name: "COVID-19 Talking Points", location: "http://teams.brookdaleliving.com/sites/sla/Quick%20Reference%20Guides/COVID-19%20Virus%20CC%20Talking%20Points%20Job%20Aid.pdf" },
  { name: "Email Additional Resources", location: "https://bkdcontactcenter.host/additional-resources/" },
  { name: "Medicaid/Medicare", location: "http://teams.brookdaleliving.com/sites/sla/Quick Reference Guides/Medicaid vs. Medicare Ven Diagram2.htm" },
  { name: "New Sales Verbiage QRG", location: "https://teams.brookdaleliving.com/sites/sla/Quick%20Reference%20Guides/CC%20Updated%20Call%20Flow%20QRG.htm" },
  { name: "Non-SL Call QRG", location: "http://teams.brookdaleliving.com/sites/sla/Quick Reference Guides/Non Senior Living Lead QRG.htm" },
  { name: "QRG Terminology Look Up", location: "https://bkdcontactcenter.host/knowledgelookup/" },
  { name: "Result of Call / Lost Closed Reasons", location: "http://teams.brookdaleliving.com/sites/sla/Quick Reference Guides/Lost Closed Reasons QRG.htm" },
  { name: "SMS", location: `${process.env.REACT_APP_SALES_URL}` },
  { name: "SNF QRG", location: "http://teams.brookdaleliving.com/sites/sla/Quick Reference Guides/SNF - SMS Lead Procedure QRG.htm" },
  { name: "Sales Verbiage QRG", location: "https://teams.brookdaleliving.com/sites/sla/Quick%20Reference%20Guides/CC%20Updated%20Call%20Flow%20QRG.htm" },
  { name: "Spanish Lead", location: "http://teams.brookdaleliving.com/sites/sla/Quick Reference Guides/Spanish Inquiries Procedure.htm" },
  { name: "Special Event RSVP Guide", location: "http://teams.brookdaleliving.com/sites/sla/Quick%20Reference%20Guides/Special%20Event%20RSVP%20Guide.htm" },
  { name: "Transfer Call Procedure", location: "http://teams.brookdaleliving.com/sites/sla/Quick Reference Guides/Transfer Call Procedure.htm" },
]
