export const fields = {
    lead: {
        influencer: {
            firstName: 'lead.influencer.firstName',
            lastName: 'lead.influencer.lastName',
            email: 'lead.influencer.email',
            phone: {
                number: 'lead.influencer.phone.number',
                type: 'lead.influencer.phone.type',
            },
            address: {
                line1: 'lead.influencer.address.line1',
                line2: 'lead.influencer.address.line2',
                city: 'lead.influencer.address.city',
                state: 'lead.influencer.address.state',
                zip: 'lead.influencer.address.zip',
            }
        },
        prospect: {
            firstName: 'lead.prospect.firstName',
            lastName: 'lead.prospect.lastName',
            email: 'lead.prospect.email',
            age: 'lead.prospect.age',
            veteranStatus: 'lead.prospect.veteranStatus',
            phone: {
                number: 'lead.prospect.phone.number',
                type: 'lead.prospect.phone.type',
            },
        },
        adlNeeds: {
            bathing: 'lead.adlNeeds.bathing',
            dressing: 'lead.adlNeeds.dressing',
            feeding: 'lead.adlNeeds.feeding',
            incontinence: 'lead.adlNeeds.incontinence',
            medications: 'lead.adlNeeds.medications',
            toileting: 'lead.adlNeeds.toileting',
            transferring: 'lead.adlNeeds.transferring',
            noAdlNeeds: 'lead.adlNeeds.noAdlNeeds',
        },
        memoryConcerns: {
            alzDiagnosis: 'lead.memoryConcerns.alzDiagnosis',
            argumentative: 'lead.memoryConcerns.argumentative',
            forgetsRepeats: 'lead.memoryConcerns.forgetsRepeats',
            wandering: 'lead.memoryConcerns.wandering',
        },
        mobilityConcerns: {
            fallRisk: 'lead.mobilityConcerns.fallRisk',
            walkerRegularly: 'lead.mobilityConcerns.walkerRegularly',
            onePersTransfer: 'lead.mobilityConcerns.onePersTransfer',
            wheelchairRegularly: 'lead.mobilityConcerns.wheelchairRegularly',
            twoPersTransfer: 'lead.mobilityConcerns.twoPersTransfer',
            caneRegularly: 'lead.mobilityConcerns.caneRegularly',
        },
        nutritionConcerns: {
            diabetesDiagnosis: 'lead.nutritionConcerns.diabetesDiagnosis',
            lowSaltLowDiet: 'lead.nutritionConcerns.lowSaltLowDiet',
            otherDietRestrictions: 'lead.nutritionConcerns.otherDietRestrictions',
            notEatingWell: 'lead.nutritionConcerns.notEatingWell',
        },
        financialOptions: {
            aidAttendance: 'lead.financialOptions.aidAttendance',
            familyContributions: 'lead.financialOptions.familyContributions',
            homeOwner: 'lead.financialOptions.homeOwner',
            ltcPolicy: 'lead.financialOptions.ltcPolicy',
        },
        drivers: {
            activities: 'lead.drivers.activities',
            accessToResidents: 'lead.drivers.accessToResidents',
            ageInPlace: 'lead.drivers.ageInPlace',
            care: 'lead.drivers.care',
            location: 'lead.drivers.location',
            peaceOfMind: 'lead.drivers.peaceOfMind',
            petFriendly: 'lead.drivers.petFriendly',
            safety: 'lead.drivers.safety',
            didNotDiscloseDriver: 'lead.drivers.didNotDiscloseDriver',
        },
        secondPerson: {
            selected: 'lead.secondPerson.selected',
            firstName: 'lead.secondPerson.firstName',
            lastName: 'lead.secondPerson.lastName',
            email: 'lead.secondPerson.email',
            phone: {
                number: 'lead.secondPerson.phone.number',
                type: 'lead.secondPerson.phone.type',
            }
        },
        notes: {
            situation: 'lead.notes.situation',
            passionsPersonality: 'lead.notes.passionsPersonality',
            financialSituation: 'lead.notes.financialSituation',
            additionalNotes: 'lead.notes.additionalNotes',
            secondPersonNote: 'lead.notes.secondPersonNote',
        },
        callerType: 'lead.callerType',
        callingFor: 'lead.callingFor',
        careType: 'lead.careType',
        currentSituation: 'lead.currentSituation',
        inquiryType: 'lead.inquiryType',
        resultOfCall: 'lead.resultOfCall',
        reasonForCall: 'lead.reasonForCall',
        leadSource: 'lead.leadSource',
        leadSourceDetail: 'lead.leadSourceDetail',
        leadSourceSubDetail: 'lead.leadSourceSubDetail',
        referralText: 'lead.referralText',
        leadSource2nd: 'lead.leadSource2nd',
        leadSourceDetail2nd: 'lead.leadSourceDetail2nd',
        leadSourceSubDetail2nd: 'lead.leadSourceSubDetail2nd',
        referralText2nd: 'lead.referralText2nd',
        umid: 'lead.umid',
    },
}